### ISSUE TITLE
Request for Pretrained Model of SRGAN

### ISSUE THREAD

**Issue by kminsoo** [SJLeo/GCC#1]
Hi. 

Do you have a plan to release the model and the pruned one of SRGAN which are trained for 130 epochs that the authors use pretrain_for_pruning.sh and train.sh ???

Thanks!

**Comment by SJLeo** [comment]
Our SRGAN experiments is conducted based on https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Super-Resolution.

**Comment by kminsoo** [comment]
Can I find the model(sr_ngf24/checkpoints/model_130.pth & sr_ngf64/checkpoints/model_100.pth) in https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Super-Resolution? 
Also, I want to ask another question.
Is it right the target budget 0.20 in train.sh? Since your pruned model is 22.79G (MACs) as presented in the main paper of GCC, the number (0.20) looks weird to me.

**Comment by SJLeo** [comment]
https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Super-Resolution didn't provide the pretrained model, but you can use the code to train models yourself.

**Comment by kminsoo** [comment]
Thanks for kindly answering my questions. 
If you have the pretrained models, could you share the models for me? 

Again thanks!

**Comment by SJLeo** [comment]
About data mismatch, we randomly crop 96×96 high-resolution images from the original images and then downsample it 4× into low-resolution images as the input of the generator duiring training stage.  Duiring testing, we use 256×256 images from Set5, Set14, BSD100, and Urban100 as input of the generator. The inconsistent size of training and test input  image is the reason why the training code is inconsistent with the data reported in the paper.

**Comment by SJLeo** [comment]
> Thanks for kindly answering my questions. If you have the pretrained models, could you share the models for me?
> 
> Again thanks!

Sorry, i only retained and uploaded the relevant models in Table1 and 2. This work was down when i was a intern at Bytedance Inc. However, other models are no longer available due to my resignation from the company.

**Comment by kminsoo** [comment]
I didn't know that. Thanks!
