### ISSUE TITLE
CelebA Dataset 

### ISSUE THREAD

**Issue by Alii-Ganjj** [SJLeo/GCC#2]
Hi, thanks for your nice repository. I have two questions:
1. I could not find the dataset downloading and partitioning codes in the `[datasets](https://github.com/SJLeo/GCC/tree/main/datasets)` directory for the CelebA dataset. I manually downloaded it, and it has `train`, `valid`, and `test` in its [PyTorch implementation](https://pytorch.org/vision/stable/datasets.html#torchvision.datasets.CelebA). The code here anticipates the directory `./dataset/celeb/train`. I would appreciate it if you elaborate on the possible connection between the partitioning schemes.
2. I ran the training and testing codes for `bash` commands for `SAGAN` and it seems that the `phase` argument is `train` in both settings. Am I doing something wrong or is it what it should be as the dataset will be set to `train` in both situations in [this line of the code](https://github.com/SJLeo/GCC/blob/e70d586d1d744244cdb15c8858706ad431f59cd4/data/sa_dataset.py#L19) in the current setting. 

Thank you in advance.

**Comment by SJLeo** [comment]
About question1: we manually downloaded the CelebA dataset from the [url](https://drive.google.com/file/d/0B7EVK8r0v71pZjFTYXZWM3FlRnM/view?usp=sharing&resourcekey=0-dYn9z10tMJOBAkviAcfdyQ).

**Comment by SJLeo** [comment]
We manually download the CelebA dataset from the [official download link](https://drive.google.com/file/d/0B7EVK8r0v71pZjFTYXZWM3FlRnM/view?usp=sharing&resourcekey=0-dYn9z10tMJOBAkviAcfdyQ).  We directory unzip the file and renamed the directory as `train`.  Then we use all downloaded images during the training and verification phases. This allows us to use more images for a stable FID calculation, as down in previous unconditional GANs (eg. StyleGAN). Therefore, the  `phase` parameter is always set as  `train`.

**Comment by SJLeo** [comment]
Thank you for your careful observation, but I can still download the file from `https://cv.snu.ac.kr/research/EDSR/benchmark.tar`.

**Comment by Alii-Ganjj** [comment]
I could not download from this link using terminal but I could access it with my browser.
I had another question: 
In [this line](https://github.com/SJLeo/GCC/blob/e70d586d1d744244cdb15c8858706ad431f59cd4/datasets/prepare_cityscapes_dataset.py#L77), you replace the `color` string type with `trainIds`. However, in the files that I downloaded from [the official website](https://www.cityscapes-dataset.com/), the only types that are available are `color`, `instanceIds`, and `labelIds`. For example, there is a sample with the following versions:
`frankfurt_000001_005184_gtFine_color.png`
`frankfurt_000001_005184_gtFine_instanceIds.png`
`frankfurt_000001_005184_gtFine_labelIds.png`
`frankfurt_000001_005184_gtFine_polygons.json`
but it has not `frankfurt_000001_005184_gtFine_trainIds.png`. Do you know which of the above ones corresponds to the one that you used in your experiments?
Thank you again!

**Comment by SJLeo** [comment]
You can refer to this [link](https://github.com/mit-han-lab/gan-compression#cityscapes-dataset) to preprocess your cityscapes dataset.
