### ISSUE TITLE
Question: why doing inference at val-set when using darts_discriminator

### ISSUE THREAD

**Issue by HuaZheLei** [SJLeo/GCC#3]
In train.py, line 147:
`  
if opt.darts_discriminator and model.teacher_model is not None: 
            val_data = next(val_dataloader)
                model.set_input(val_data)
                model.clipping_mask_alpha()
                model.optimizer_netD_arch()
`
Why do you inference on val-set when using darts_discriminator? And in this situation, length of val should equal to length of train, so it will cause a bug

**Comment by SJLeo** [comment]
We apologize for the misunderstanding caused by the wrong naming. The images contained in `train_dataloade`r and `val_dataloader` are all from the `train` folder, you can check it in the [link](https://github.com/SJLeo/GCC/blob/e70d586d1d744244cdb15c8858706ad431f59cd4/data/__init__.py#L52).
