### ISSUE TITLE
reducing the memory usage of get_real_stat.py

### ISSUE THREAD

**Issue by seekingdeep** [SJLeo/GCC#4]
@SJLeo hi there,

get_real_stat.py requires alot of memory when using a large dataset,
the solution could be by storing the image tensor on the disk and then modifying the [dataloader](https://github.com/SJLeo/GCC/blob/main/metric/fid_score.py#L189) to restore the tensors from the disk.

This issue was discussed in [here](https://github.com/mit-han-lab/gan-compression/issues/44)

**Comment by SJLeo** [comment]
Thank you for your suggestion！
