### ISSUE TITLE
documentation on training pix2pix from scratch

### ISSUE THREAD

**Issue by seekingdeep** [SJLeo/GCC#5]
@SJLeo Hi there,
when wanting to train own dataset with size 256*256
what are the step-by-step to train from scratch

**Comment by SJLeo** [comment]
First of all, you have to divide the dataset according to the training task mode. For the specific dataset mode, please refer to the `data` folder. After that, modify the dataset_mode parameter and specify the dataroot parameter to the dataset directory.
