### ISSUE TITLE
Will model be further enhanced efficiency with separable convolution?

### ISSUE THREAD

**Issue by kasim0226** [SJLeo/GCC#6]
Thank you for your great work.

I am wondering if model can be further enhanced efficiency with resnet?
Because the resnet in pixel2pixel in your codes are separable convolution from efficientNet.
Did you ever test it with your method?

Looking forward to your reply.

**Comment by SJLeo** [comment]
We also conducted simple experiments on resnet, which also verified the effectiveness of our method. You can also modify the code for related experiments.
