### ISSUE TITLE
Cyclegan_binarysearch_cfg not working.

### ISSUE THREAD

**Issue by DJun0003** [SJLeo/GCC#9]
Thank you for your great work.

Unfortunately, I tried to pruning after pretraining cyclegan, but in the cyclegan_binarysearch_cfg code, the number of channels in on layer became 0 and an error occurred. May I know how to solve it?
And after setting cfg_AtoB in cyclegna_binarysearch_cfg code, cfg_AtoB is manually set again on the next line, is there any reason to do this?

Thanks

**Comment by SJLeo** [comment]
In the pruning process of cyclegan, we also encounter this problem, so we limit the pruning rate of each layer.
As for repeated cfg_AtoB, the manually set cfg_AtoB is the one that has been verified to be effective before.
